version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file: .env
    user: 1000:1000

volumes:
  postgres:
